services:
  - type: web
    name: manas-mantra-backend
    runtime: node
    buildCommand: npm install --prefix backend && npm install --prefix frontend && npm run build --prefix frontend
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /

  - type: web
    name: manas-mantra-frontend
    runtime: static
    buildCommand: npm install --prefix frontend && npm run build --prefix frontend
    staticPublishPath: ./frontend/dist
    routes:
      - path: /
        destination: /index.html
